version: "3.9"
services:
  app:
    container_name: g_shop_backend
    image: gshop/g_shop_backend:latest
    restart: always
    environment:
      NODE_ENV: production
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    external_links:
      - mongo
    depends_on:
      - mongo

  ui:
    container_name: g_shop_frontend
    image: gshop/g_shop_frontend:latest
    restart: always
    build:
      context: ./ui/
      dockerfile: Dockerfile
  mongo:
    image: mongo
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"
