version: "3.9"
services:
  app:
    build: ./backend/
    ports:
      - "8080:8080"
    networks:
      - backend

  ui:
    build: ./ui/
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
