FROM node:12

# Create app directory
WORKDIR /usr/src/app
RUN apt update &&  apt install -y dumb-init

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install -g nodemon

# Bundle app source
COPY . .

EXPOSE 8080
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD [ "nodemon", "app.js" ]